### ISSUE TITLE
Fetch Profile Data

### ISSUE THREAD

**Issue by milojezek** [milojezek/chickenbook#30]
When the user selects a profile and wants to see its details we fetch the particular profile data. It would be best to create a hook that takes a username and fetches the data based on the username. This hook is implemented in the detail page afterwards.

Definition of done:
- [x] There's a hook that takes a username and fetches profile data based on the username.
- [x] The detail page displays a profile with the data fetched with the hook.

**Comment by VeveCambor** [comment]
Do you want to work on it? or should I try?

**Comment by milojezek** [comment]
@VeveCambor Sure, you can :) I can help you if you need or have a lot of work.

**Comment by milojezek** [comment]
It's being resolved within the issue 👇
- #29
